// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301145922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Expense", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReceiptData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ReceiptName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserDept")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = "se1",
                            Amount = 18500m,
                            Category = 0,
                            Date = new DateTime(2026, 1, 30, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Description = "Annual AWS conference in Las Vegas. Covers flight, hotel, and registration.",
                            ReceiptName = "aws_receipt.pdf",
                            ReviewNote = "Approved – great conference.",
                            ReviewedAt = new DateTime(2026, 2, 1, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 1, 30, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Title = "AWS re:Invent Conference",
                            UserDept = "Engineering",
                            UserId = "demo_emp",
                            UserName = "Alex Lee"
                        },
                        new
                        {
                            Id = "se2",
                            Amount = 2400m,
                            Category = 1,
                            Date = new DateTime(2026, 2, 14, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Description = "Team lunch for sprint retrospective.",
                            ReviewNote = "",
                            ReviewedAt = new DateTime(2026, 2, 15, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 2, 14, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Title = "Team Lunch",
                            UserDept = "Engineering",
                            UserId = "demo_emp",
                            UserName = "Alex Lee"
                        },
                        new
                        {
                            Id = "se3",
                            Amount = 1200m,
                            Category = 4,
                            Date = new DateTime(2026, 2, 24, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Description = "Monthly GitHub Copilot Business license.",
                            ReviewNote = "",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 2, 24, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Title = "GitHub Copilot Subscription",
                            UserDept = "Engineering",
                            UserId = "demo_emp",
                            UserName = "Alex Lee"
                        },
                        new
                        {
                            Id = "se4",
                            Amount = 12999m,
                            Category = 3,
                            Date = new DateTime(2026, 2, 9, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Description = "Herman Miller Aeron for home office setup.",
                            ReceiptName = "chair_invoice.jpg",
                            ReviewNote = "Exceeds ₹10,000 policy limit without prior CFO approval. Please resubmit with approval form.",
                            ReviewedAt = new DateTime(2026, 2, 11, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 2, 9, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Title = "Ergonomic Office Chair",
                            UserDept = "Engineering",
                            UserId = "demo_emp",
                            UserName = "Alex Lee"
                        },
                        new
                        {
                            Id = "se5",
                            Amount = 5800m,
                            Category = 6,
                            Date = new DateTime(2026, 2, 26, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Description = "Business dinner with Infosys team leads.",
                            ReceiptName = "dinner_receipt.png",
                            ReviewNote = "",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 2, 26, 14, 59, 19, 531, DateTimeKind.Utc).AddTicks(3518),
                            Title = "Client Dinner – Infosys",
                            UserDept = "Engineering",
                            UserId = "demo_emp",
                            UserName = "Alex Lee"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "demo_emp",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "employee@demo.com",
                            Fname = "Alex",
                            Lname = "Lee",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = 0
                        },
                        new
                        {
                            Id = "demo_mgr",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Email = "manager@demo.com",
                            Fname = "Morgan",
                            Lname = "Grant",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
